appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c342c7a302eb707003cf01c
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: HjdCseexgokxugEmDUYMT7CHRYmTW8/jzB8oV16HbhDIXJ7B55Kfr6qCmBFc7mJfGUXn3nfoSZuPn5BWbjwAQ9e8vT7LvLNFVgfuwHqfcUxcXUyyO+/LiSfbe0Up1GGSkN1JAwjQnDMm6GlRfqQ42Adp1HtZu1mI6lADO1baSIyxwQPD2to74eDrqsjt/K1fD7TZFr73+PIE4WxT0otS0omnn3MWZOPOg+csF2Rc/UCccLpmMTZlg435yZapG3tXqIGzz9k7DC0AIX4F6TG0TQVD14QFzN1NBN0D7sw8TXjy+5sdATHgLJ7SnQbIFmtUby5ir6QqYA7dej6Cng35byLrbtnAolKsInCtHcvfvJBBxpneha8TBAJHdTtGAiXaLUMeAmOoL/youcl4Ecc3hHW+oVw5gidIwloryoLRkKRH7VwYa8xuUO2AYzOaR1E23jsMBwIIW8WEUL17jCSC52Mrw3I25r/q3Z56ubLW8KU5HA47pbUoBMBHXVoy/Bw3dQV8xnvD4fzNoF5OWkF8HSsBkAKg+3KJagKiBdT7lkSw1Sp8H6kCHxOY00h4e5no186la/FQZEVf1zm2RFfd7f6qZzYC97jP3ALFlXiINRje07LszM1z/PU3Ut9Q2x9LwckidSks5aI8ZChyJ2wciMDmXGarA8jL3S8Ss6orJw0=}
